# Use Node.js LTS version as the base image
FROM node:20-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Install dependencies
RUN npm install 

# Define build arguments for environment variables
ARG PORT
ARG DB_URL
ARG DB_NAME
ARG MJ_APIKEY_PUBLIC
ARG MJ_APIKEY_PRIVATE
ARG MAIL_USER
ARG MAIL_PASSWORD
ARG GOOGLE_CLIENT_ID
ARG JWT_SECRET
ARG GOOGLE_CLIENT_SECRET
ARG BASE_URL
ARG ISSUER_BASE_URL
ARG FACEBOOK_APP_ID
ARG FACEBOOK_APP_SECRET
ARG REDIRECT_URI
ARG SESSION_SECRET
ARG CLIENT_URI
ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET
ARG USER_DEFAULT_IMAGE_PUBLICID
ARG ADVICE_DEFAULT_IMAGE_PUBLICID
ARG ADVERTISEMENT_DEFAULT_IMAGE_PUBLICID
# Set environment variables from build arguments
ENV PORT=$PORT
ENV DB_URL=$DB_URL
ENV DB_NAME=$DB_NAME
ENV MJ_APIKEY_PUBLIC=$MJ_APIKEY_PUBLIC
ENV MJ_APIKEY_PRIVATE=$MJ_APIKEY_PRIVATE
ENV MAIL_USER=$MAIL_USER
ENV MAIL_PASSWORD=$MAIL_PASSWORD
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV JWT_SECRET=$JWT_SECRET
ENV BASE_URL=$BASE_URL
ENV ISSUER_BASE_URL=$ISSUER_BASE_URL
ENV FACEBOOK_APP_ID=$FACEBOOK_APP_ID
ENV FACEBOOK_APP_SECRET=$FACEBOOK_APP_SECRET
ENV REDIRECT_URI=$REDIRECT_URI
ENV SESSION_SECRET=$SESSION_SECRET
ENV CLIENT_URI=$CLIENT_URI
ENV CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME
ENV CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
ENV CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET
ENV USER_DEFAULT_IMAGE_PUBLICID=$USER_DEFAULT_IMAGE_PUBLICID
ENV ADVICE_DEFAULT_IMAGE_PUBLICID=$ADVICE_DEFAULT_IMAGE_PUBLICID
ENV ADVERTISEMENT_DEFAULT_IMAGE_PUBLICID=$ADVERTISEMENT_DEFAULT_IMAGE_PUBLICID

# Bundle app source
COPY . .

# Expose the port the app runs on
EXPOSE ${PORT}

# Command to run the application
CMD ["node", "app.js"]